# Generated by Django 5.2.17 on 2026-09-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Not started'), ('progress', 'In progress'), ('review', 'Waiting for review'), ('done', 'Completed'), ('changes', 'Changes requested')], default='todo', max_length=10),
        ),
    ]
